services:
  app:
    build: .
    container_name: gestion-facturation-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gestion_facturation?schema=public
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000 # Changer pour le domaine r√©el en PROD
      - NEXTAUTH_SECRET=changeme_in_prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: gestion-facturation-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gestion_facturation
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gestion_facturation"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
